### ISSUE TITLE
Provide a public issue tracker

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/labs.geodata.gov.gr#105]
Having a public issue tracker for public to submit issues with geodata.gov.gr would be very helpful.

**Comment by kalxas** [comment]
https://github.com/PublicaMundi/geodata.gov.gr/issues is to be used for reports from users, citizens etc.

**Comment by kalxas** [comment]
@drmalex07 @smanousopoulos @SpirosAthanasiou any suggestions on where to link this on our first page? Or perhaps better on the Developers page?

**Comment by drmalex07** [comment]
Maybe something like 'Report an issue' on the footer? 
I dont think it should be under 'Developers' because it discourages the majority of end users (e.g a survey/civil engineer will probably also leave valuable feedack)

**Comment by kalxas** [comment]
@drmalex07 :+1:

**Comment by drmalex07** [comment]
@kalxas This one is ready also (check at labs.geodata.gov.gr). Of course it requires a user to have a GitHub account (or to be able to login via OpenID)

**Comment by kalxas** [comment]
sounds great, thanks
