### ISSUE TITLE
Harvesting INSPIRE catalogues

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/labs.geodata.gov.gr#140]
Implement a harvester to parse INSPIRE metadata through our schematics extension

**Comment by drmalex07** [comment]
@kalxas Maybe move this one under ckanext-publicamundi?

**Comment by kalxas** [comment]
Yes I will move it there

**Comment by kalxas** [comment]
https://github.com/PublicaMundi/ckanext-publicamundi/issues/219
