### ISSUE TITLE
Process Table Implementation

### ISSUE THREAD

**Issue by gfenoy** [PublicaMundi/labs.geodata.gov.gr#89]
For having the capability to implement the *Dismiss* request we have to first have a way to store informations (including jobId - corresponding to the current sid from the lenv section in the main.cfg -, state - running / paused / ended -, file name used to store the result, memory usage statistics, the time to wait for the next poll - GetStatus - request) about services (even for those which ended already).

linked with #87

**Comment by kalxas** [comment]
Completed
